[build]
  command = "npm run build"
  publish = "out"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["SPA"]}

# Serve static pages directly
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/analytics"
  to = "/analytics/index.html"
  status = 200

[[redirects]]
  from = "/customers"
  to = "/customers/index.html"
  status = 200

[[redirects]]
  from = "/products"
  to = "/products/index.html"
  status = 200

[[redirects]]
  from = "/visitors"
  to = "/visitors/index.html"
  status = 200

[[redirects]]
  from = "/engagement"
  to = "/engagement/index.html"
  status = 200

[[redirects]]
  from = "/automation"
  to = "/automation/index.html"
  status = 200

[[redirects]]
  from = "/integrations"
  to = "/integrations/index.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/projects/index.html"
  status = 200

[[redirects]]
  from = "/segment"
  to = "/segment/index.html"
  status = 200

# Fallback for 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build.environment]
  NODE_VERSION = "20"
